// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxl_VSqGncHP7EUBS9uE56ZSmxGKPeLpc',
    appId: '1:1094976994314:web:0b48ecf5d22b1e847273f3',
    messagingSenderId: '1094976994314',
    projectId: 'notifypush-179a1',
    authDomain: 'notifypush-179a1.firebaseapp.com',
    storageBucket: 'notifypush-179a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6W8jpEFiqDLD5vJL4dPit_SpDsbNVbdE',
    appId: '1:1094976994314:android:a71f675b1d2125747273f3',
    messagingSenderId: '1094976994314',
    projectId: 'notifypush-179a1',
    storageBucket: 'notifypush-179a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvPWEgPe7zADsGOSRXfyE8wrb6Gbu0oY',
    appId: '1:1094976994314:ios:bfc8fbbee8a7376c7273f3',
    messagingSenderId: '1094976994314',
    projectId: 'notifypush-179a1',
    storageBucket: 'notifypush-179a1.appspot.com',
    iosBundleId: 'com.example.pruebaNotificacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvPWEgPe7zADsGOSRXfyE8wrb6Gbu0oY',
    appId: '1:1094976994314:ios:425254263a74d75f7273f3',
    messagingSenderId: '1094976994314',
    projectId: 'notifypush-179a1',
    storageBucket: 'notifypush-179a1.appspot.com',
    iosBundleId: 'com.example.pruebaNotificacion.RunnerTests',
  );
}
